name: Deploy to Staging

on:
  push:
    branches:
      - main 

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: STG 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: |
          echo "Ensuring STG deployment requirement met..."

