name: Deploy to Staging

on:
  push:
    branches:
      - develop-v1

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: STG 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: |
          echo "Ensuring STG deployment requirement met..."

      - name: Install maven repo and authorize
        run: |
          echo "Installing Java, mvn, and configuring step... "
          echo "MY_MVN_INSTALL" > maven.install.mock

      - name: Viewing mvn install
        run: |
          cat maven.install.mock

